# Generated by Django 3.0.7 on 2020-06-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='order_number',
            new_name='wishlist_number',
        ),
    ]
