# Generated by Django 3.0.7 on 2020-06-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20200626_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist_number',
        ),
    ]
