# Generated by Django 3.0.7 on 2020-06-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_auto_20200626_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='lineitem_total',
            new_name='wishlistitem_total',
        ),
    ]
