# Generated by Django 3.0.7 on 2020-07-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_auto_20200627_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Wishlist_total',
            new_name='wishlist_total',
        ),
    ]
