# Generated by Django 3.0.7 on 2020-06-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='date',
        ),
    ]
