# Generated by Django 3.0.7 on 2020-06-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200607_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='1393882962', max_length=10, unique=True),
        ),
    ]
