# Generated by Django 3.0.8 on 2020-07-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_full_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_slug',
            field=models.CharField(default=models.CharField(max_length=254, unique=True), max_length=254),
        ),
    ]
