# Generated by Django 3.0.8 on 2020-07-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200707_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, default='/media/static/media/default/default_subcategory.jpg', null=True, upload_to='category'),
        ),
    ]
