# Generated by Django 3.0.8 on 2020-07-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200707_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default_category.jpg', null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, default='/media/defaults/default_subcategory.jpg', null=True, upload_to='category'),
        ),
    ]
