# Generated by Django 3.0.8 on 2020-07-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200707_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_image_url',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
