# Generated by Django 3.0.8 on 2020-07-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_full_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default_product.jpg', null=True, upload_to='product'),
        ),
    ]
