# Generated by Django 3.0.8 on 2020-07-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200707_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='full_image_url',
        ),
    ]
